{{- if .Values.spec.enabled }}
kind: Service
apiVersion: v1
metadata:
  #name: {{quote .Values.labels.AppName }}
  name: {{ .Chart.name }}
  labels:
    #service: {{quote .Values.labels.AppName }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    #AppName: {{quote .Values.labels.AppName }}
    #AppVersion: {{quote .Values.labels.AppVersion }}
    app: {{quote .Values.labels.AppName }}
    tier: {{quote .Values.labels.tierType }}
spec:
  type: {{ .Values.spec.type }}
  selector:
    #AppName: {{quote .Values.labels.AppName }}
    app: {{quote .Values.labels.AppName }}
    tier: {{quote .Values.labels.tierType }}
  ports:
    - port: {{ .Values.spec.port }}
      nodePort: {{ .Values.spec.nodePort }}
      targetPort: {{ .Values.spec.targetPort }}
      #protocol: TCP
      #name: http
{{ end }}
