replicaCount: 1

labels:
  AppName: hello
  ContainerName: hello-app
  AppVersion: "apps/v1"
  tierType: web
  specType: LoadBalancer
  specPorts: 80
  specNodePort: 8080
  specTargetPort: 8080

image:
  #repository: dockerworkshopdallas/java
  repository: us-docker.pkg.dev/google-samples/containers/gke/hello-app:2.0
  tag: release
  pullPolicy: IfNotPresent
  containerPort: 8080
  cpuRes: 200m
