replicaCount: 1

labels:
  AppName: hello
  ContainerName: hello-app
  AppVersion: "apps/v1"

image:
  repository: dockerworkshopdallas/java
  tag: release
  pullPolicy: IfNotPresent
  containerPort: 8080
